services:
  backend:
    build: ./backend
    environment:
      HOST: 10.128.0.3
      PORT: 5050
    depends_on:
      - resilientdb
      - resilientdb-graphql-server
    network_mode: "host"

  frontend:
    build: ./frontend
    environment:
      HOST: 10.128.0.3
      PORT: 3000
      REACT_APP_BACKEND: http://34.41.126.42:5050
    depends_on:
      - backend
    network_mode: "host"

  resilientdb:
    image: expolab/resdb:amd64
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/10001"]
      interval: 5s
      retries: 300
      start_period: 30s
    network_mode: "host"

  resilientdb-graphql-crow:
    build: ./resilientdb-graphql
    platform: linux/amd64
    entrypoint: ["/bin/bash", "-c"]
    command: ["bazel-bin/service/http_server/crow_service_main service/tools/config/interface/service.config service/http_server/server_config.config"]
    depends_on:
      resilientdb:
        condition: service_healthy
    network_mode: "host"

  resilientdb-graphql-server:
    build: ./resilientdb-graphql
    platform: linux/amd64
    entrypoint: ["/bin/bash", "-c"]
    command: ["python3.10 app.py"]
    depends_on:
      resilientdb:
        condition: service_healthy
    network_mode: "host"
